#!/bin/sh

# Syncs membership reg into keymaster
# Last Updated 2017-03-09 ben@generik.ca

# get database info from env file
.  /var/www/kos-base/.env

DATESTAMP=`date +%Y-%m-%d`

# backup users table from database
mysqldump --user=$DB_USERNAME --password=$DB_PASSWORD $DB_DATABASE users > /var/www/kos-base/backups/users-$DATESTAMP.sql

# remove old repo
rm -rf /var/www/kos-base/storage/import/membershipreg

# get the current register of active members
cd /var/www/kos-base/storage/import
git clone git@github.com:kwartzlab/membershipreg.git

# change permissions so apache can read the files
#chown -R doc.www-data /var/www/storage/import

# run keymaster import command via composer
#cd /var/www/kos-base
#php artisan sync:members /var/www/kos-base/storage/import/membershipreg/members.csv

